<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="src\AccioData29.CoordinatorWorker.Domain\AccioData29.CoordinatorWorker.Domain.csproj" />
    <ProjectReference Include="src\AccioData29.CoordinatorWorker.Application\AccioData29.CoordinatorWorker.Application.csproj" />
  </ItemGroup>
</Project>
